### ISSUE TITLE
ace-jump-buffer other window?

### ISSUE THREAD

**Issue by milkypostman** [waymondo/ace-jump-buffer#4]
would it be easy to add an `ace-jump-buffer-other-window` function that would load the buffer in the other window?

so far I am liking this. Is it robust enough to use for a total `switch-buffer` replacement? i assume it caps at 24 buffers.

**Comment by rswgnu** [comment]
Here's a patch to allow use of a prefix arg with ace-jump-buffer to display the selected buffer in the other window, so that you need only one key binding for same or other window placement.  Nice and simple:

(defun ace-jump-buffer (&optional other-win-flag)
  "Quickly hop to buffer with `avy'."
  (interactive "P")
  (let ((ajb/other-window other-win-flag)
	(avy-background nil)
        (avy-all-windows nil)
        (bs-attributes-list ajb/bs-attributes-list)
        (avy-handler-function 'ajb/exit)
        (avy-style ajb-style)
        (ajb/showing t))
    (save-excursion
      (bs--show-with-configuration ajb-bs-configuration)
      (set (make-local-variable 'bs-header-lines-length) 0)
      (set (make-local-variable 'bs-max-window-height) ajb-max-window-height)
      (face-remap-add-relative 'default 'ajb-face)
      (goto-char (point-min))
      (bs--set-window-height)
      (ajb/goto-line-and-buffer))))
