### ISSUE TITLE
Don't show current buffer at head of list

### ISSUE THREAD

**Issue by orki** [waymondo/ace-jump-buffer#7]
How can I move the current buffer to the end of the list that is shown? It is very unlikely that I want to switch to the buffer I am currently in when invoking ace-jump-buffer. However, the current buffer is always at the head of the list. I tried to fix it as follows, but it did not work:

    (defvar ravi/buffer-before-switch nil)
    (defun ravi/bs-sort-function (b1 b2)
      (if (eq b1 ravi/buffer-before-switch)
          nil
        (if (eq b2 ravi/buffer-before-switch)
            t
          (bs--sort-by-recentf b1 b2)))
      )
    (defadvice ace-jump-buffer (around dont-show-current-buffer activate)
      (let ((ravi/buffer-before-switch (current-buffer)))
        ad-do-it))
    (setq ajb-sort-function 'ravi/bs-sort-function)

**Comment by waymondo** [comment]
The sort function will still display the buffer even if you still return nil in `ravi/bs-sort-function`. Returning `t` just effects the order.

The way to limit the buffers used to use the [macro](https://github.com/waymondo/ace-jump-buffer#macro) to create a function which filters out the current buffer, like:

```
(make-ace-jump-buffer-function "without-current-buffer"
  (let ((curr-buff (current-buffer)))
    (with-current-buffer buffer
      (eq buffer curr-buff))))
```

Then you could call `ace-jump-without-current-buffer-buffers`.

This doesn't work though because `bs` internally forces the `(current-buffer)` back into the buffer list. This could probably be circumvented in some creative `defadvice` but I'm personally fine with the current behavior.

Hope this helps and let me know if you come up with a solution.
