### ISSUE TITLE
why not choose buffer like ace-jump-mode using the first chars of the names of buffers?

### ISSUE THREAD

**Issue by yangguang760** [waymondo/ace-jump-buffer#8]

**Comment by waymondo** [comment]
I chose `ace-jump-line-mode` over `ace-jump-word-mode` because it ensures the buffer hopping flow only requires 2 keystrokes.

With `ace-jump-line-mode`:

* Invoke the buffer list
* Choose the letter of the line with the buffer you want

With `ace-jump-word-mode`:

* Invoke the buffer list
* Hit the first letter of the buffer you want
* Choose the instance of the buffer if there is more than 1 that begin with that letter

If this is still more desirable for you, please feel free to take a crack at opening a PR with this support.
